name: Package Chrome Extension

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create getPassKey.js
        run: echo "export default function() { return 'Wh@tAr3Y0uDoing?'; }" > ./src/utils/getPassKey.js

      - name: Build and package Chrome extension
        run: yarn build

      - name: Find the generated manifest.json
        id: find_manifest
        run: echo "MANIFEST_PATH=$(find build/* -type f -name 'manifest.json')" >> $GITHUB_ENV

      - name: Insert RSA key into manifest.json
        run: |
          jq --arg key "$PUBLIC_RSA_KEY" '.key = $key' $MANIFEST_PATH > temp.json && mv temp.json $MANIFEST_PATH
        env:
          PUBLIC_RSA_KEY: ${{ secrets.PUBLIC_RSA_KEY }}

      - name: Build and package Chrome extension
        run: yarn build:zip

      - name: Find the generated zip file
        id: find_zip
        run: echo "ZIP_PATH=$(find build-zip/* -type f -name '*.zip')" >> $GITHUB_ENV

      - name: Get current date and time
        id: date
        run: echo "RELEASE_TAG=release-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }} # Unique tag with date and time
          release_name: "Automated Release - ${{ env.RELEASE_TAG }}"
          body: "This release was automatically generated."
          draft: false
          prerelease: false

      - name: Upload Chrome extension ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: automa_chrome_extension.zip
          asset_path: ${{ env.ZIP_PATH }}
          asset_content_type: application/zip
          
